Repository LLMQuant/quant-mind, pull requests merged in 2025-04, with the labels that each got.

#16 [Feature] Add the backbone of our `autoscholar` and a simple draft.
  .env-example
  .gitignore
  SETUP.md
  asset/demo-kg-abstract.png
  autoscholar/__init__.py
  autoscholar/embeddings/__init__.py
  autoscholar/embeddings/base.py
  autoscholar/embeddings/gemini_embedding.py
  autoscholar/embeddings/openai_embedding.py
  autoscholar/knowledge/__init__.py
  autoscholar/knowledge/graph_builder.py
  autoscholar/knowledge/knowledge_graph.py
  autoscholar/knowledge/paper.py
  autoscholar/scholar_summary/demo/2503.08696.pdf
  autoscholar/scholar_summary/demo/2503.08696/2503.08696.md
  autoscholar/scholar_summary/demo/2503.08696/2503.08696_meta.json
  autoscholar/scholar_summary/demo/2503.08696/_page_10_Figure_0.jpeg
  autoscholar/scholar_summary/demo/2503.08696/_page_5_Figure_0.jpeg
  autoscholar/scholar_summary/demo/2503.08696/_page_6_Figure_0.jpeg
  autoscholar/scholar_summary/demo/2503.08696/_page_6_Figure_2.jpeg
  autoscholar/scholar_summary/demo/2503.08696/_page_7_Figure_5.jpeg
  autoscholar/scholar_summary/demo/2503.08696/demo_summary.pdf
  autoscholar/scholar_summary/demo/2503.08696/demo_summary.tex
  autoscholar/scholar_summary/demo/demo.py
  autoscholar/scholar_summary/demo/template.tex
  autoscholar/types/__init__.py
  autoscholar/types/embedding_types.py
  autoscholar/utils/logger.py
  autoscholar/utils/similarity.py
  autoscholar/visualization/graph_visualizer.py
  examples/kg_by_abstract/README.md
  examples/kg_by_abstract/demo.py
  examples/kg_by_abstract/example-data/2502.15458.json
  examples/kg_by_abstract/example-data/2502.15611.json
  examples/kg_by_abstract/example-data/2502.15853.json
  examples/kg_by_abstract/example-data/2502.16023.json
  examples/kg_by_abstract/example-data/2502.17044.json
  examples/kg_by_abstract/example-data/2502.17967.json
  examples/kg_by_abstract/example-data/2502.18177.json
  examples/kg_by_abstract/example-data/2502.19305.json
  examples/kg_by_abstract/example-data/2502.20978.json
  examples/kg_by_abstract/example-data/2503.00603.json
  examples/kg_by_abstract/example-data/2503.02518.json
  examples/kg_by_abstract/example-data/2503.02680.json
  examples/kg_by_abstract/example-data/2503.03612.json
  examples/kg_by_abstract/example-data/2503.08692.json
  examples/kg_by_abstract/example-data/2503.08693.json
  examples/kg_by_abstract/example-data/2503.08696.json
  examples/kg_by_abstract/example-data/2503.08697.json
  examples/kg_by_abstract/example-data/2503.13950.json
  examples/kg_by_abstract/example-data/2503.15403.json
  examples/kg_by_abstract/example-data/2503.16470.json
  examples/kg_by_abstract/example-data/embeddings/embeddings.json
  pyproject.toml
  requirements.txt
  scripts/lint.sh
  scripts/unittest.sh
  tests/knowledge/test_knowledge_graph.py
  tests/knowledge/test_paper.py
  uv.lock
Labels: enhancement, Task

#19 [Feature] Add a simple pre-commit setup config.
  .pre-commit-config.yaml
  SETUP.md
  scripts/lint.sh
  scripts/pre-commit-setup.sh
Labels: Task

#24 [Fix] Bypass branch rule.
  .github/workflows/quant_scholar.yml
  README.md
  docs/quant-scholar.json
  wiki/index.md
Labels: bug

#17 [Feature] Integrate marker library for PDF to Markdown conversion
  README.md
  autoscholar/parser/__init__.py
  autoscholar/parser/parse_tool.py
  autoscholar/parser/pdf_parser.py
  autoscholar/scholar_summary/demo/demo.py
  docs/quant-scholar.json
  tests/parser/test_pdfparse.py
  wiki/index.md
Labels: Task

#26 [Feature] Support LlamaParse and add corresponding example.
  .env-example
  autoscholar/parser/llama_parser.py
  autoscholar/parser/parse_tool.py
  examples/parser/llama_parser_example.ipynb
  examples/parser/test-pdf.pdf
  pyproject.toml
  uv.lock
Labels: enhancement
